version: '3.7'

services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: ${{ secrets.PROJECT_DATABASE_NAME }}
      MYSQL_PASSWORD: ${{ secrets.PROJECT_DATABASE_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${{ secrets.PROJECT_DATABASE_USERNAME }}
    ports:
      - '3306:3306'

  app:
    build: .
    ports:
      - '8081:8040'  # Adjust port as needed
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${{ secrets.PROJECT_DATABASE_NAME }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.PROJECT_DATABASE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.PROJECT_DATABASE_PASSWORD }}

